<?php

namespace App;

use App\Libs\UUIDGenerator;
use Illuminate\Database\Eloquent\Model;

/**
 * Class DoctorSchedule
 * @package App
 */
class DoctorSchedule extends Model
{
    //
    use UUIDGenerator;

    /**
     * @var string
     */
    protected $table = "doctor_schedule";
    /**
     * @var bool
     */
    public $incrementing = false;
    /**
     * @var bool
     */
    public $timestamps = false;

    protected $casts = [
        'id' => 'string',
        'doctor_id' => 'string'
    ];

    public function getDoctorIdAttribute($value)
    {
        return (string) "$value";
    }

    public function getIdAttribute($value)
    {
        return (string) "$value";
    }

    protected $primaryKey = "id";

    public function getForeignKey()
    {
        return (string) "$this->doctor_id"; // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getPrimaryKey(): string
    {
        return (string) "$this->primaryKey";
    }
}
